apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend-tomcat
  name: backend-tomcat
  namespace: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-tomcat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend-tomcat
    spec:
      containers:
      - image: public.ecr.aws/e6m3e0t8/h1998yc:tomcat_v2.1
        name: h1998yc
        resources: {}
status: {}