apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend-nginx
  name: web-was-svc
  namespace: front-end
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend-nginx
  type: LoadBalancer
status:
  loadBalancer: {}