apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend-nginx
  name: frontend-nginx
  namespace: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend-nginx
    spec:
      containers:
      - image: public.ecr.aws/e6m3e0t8/h1998yc:nginx_v2.6
        name: h1998yc
        resources: {}
status: {}